package:
  name: jaeger
  version: 1.76.0 # Keep in sync with version in sg.config.yaml
  epoch: 0
  description: "Distributed Tracing Platform"
  target-architecture:
    - x86_64
  copyright:
    - paths:
        - "*"
      attestation: 'Copyright The Jaeger Authors'
      license: 'Apache License 2.0'
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/jaegertracing/jaeger/releases/download/v${{package.version}}/jaeger-${{package.version}}-linux-amd64.tar.gz
      expected-sha256: cab3ead06a837ee519c16a4394b323e58b66b4f2f8f82c0db0dfb81035def72e
      extract: true
      strip-components: 0

  - runs: |
      set -x
      mkdir -p ${{targets.destdir}}/usr/local/bin/
      mv jaeger-${{package.version}}-linux-amd64/* ${{targets.destdir}}/usr/local/bin/

subpackages:
  - name: jaeger-agent
    description: Jaeger Agent
    pipeline:
      - runs: |
          set -x
          mkdir -p "${{targets.subpkgdir}}/usr/local/bin/"
          cp "${{targets.destdir}}/usr/local/bin/jaeger-agent" "${{targets.subpkgdir}}/usr/local/bin/"

  - name: jaeger-all-in-one
    description: Jaeger All-In-One
    pipeline:
      - runs: |
          set -x
          mkdir -p "${{targets.subpkgdir}}/usr/local/bin/"
          cp "${{targets.destdir}}/usr/local/bin/jaeger-all-in-one" "${{targets.subpkgdir}}/usr/local/bin/"

update:
  enabled: true
  github:
    identifier: jaegertracing/jaeger
    strip-prefix: "v"
